DOCKER_USER=qserv
MASTER=ccqserv125.in2p3.fr
BRANCH=tickets_DM-4943
MASTER_IMAGE="$DOCKER_USER/qserv:${BRANCH}_master_$MASTER"
WORKER_IMAGE="$DOCKER_USER/qserv:${BRANCH}_worker_$MASTER"
CONTAINER_NAME=qserv_dev
